### PR TITLE
added a quick gralde build

### PR DESCRIPTION
**Pull request by nathandunn**

### CODE REVIEW

**Comment by nathandunn** [comment]
I created this with "gradle init" . .  it will automatically create the appropriate files.   the build.gradle file is the meat of it.  gradlew is just a wrapper if you don't want to install gradle.

**Comment by cmungall** [comment]
Is this intended to replace the pom?

If so, what are the advantages (I personally prefer the syntax of gradle but poms are very standard for java projects)

If not, we will presumably have to manually sync the two?

**Comment by nathandunn** [comment]
I would replace the pom.  

So gradle is a pretty popular standard for java projects, so I think that we are pretty safe to adopt it, especially for simpler projects.   

The advantages (other than readability), is that you can script it using groovy directly, which is nice for simple stuff.  It replaces a lot of what ant does, including its make-like dependency resolution, except that it doesn’t use XML.  It uses the exact same dependency resolution mechanism and an almost identical (though configurable) file structure as maven (which is maven’s biggest advantage IMO), but produced the same types of outputs (jars, embedded servers, executing unit tests, support for any JVM language etc.).    

The big difference is that the dearth of available plugins . . though gradle is catching up.   Anyway, for me its a no-brainer for most standard targets.    

Nathan

**Comment by nathandunn** [comment]
@cmungall   I had forgotten to check in a few things travis needed to use "gradlew".  Is working now.  I also removed the pom.xml.  No worries if you want to head another direction, but I think this is fast becoming a new standard.  I think that @jnguyenx has also worked with these and so he might have some suggestions as well.

**Comment by jnguyenx** [comment]
I have mixed feelings about gradle. It was already the "fast becoming
standard" when I started working with it 5 years ago.
I think that it still has a long way to go before replacing maven (
http://www.indeed.com/jobtrends/maven%2C+gradle.html)

With that said, I'm not totally against using gradle, as long as we don't
use any gradle specifics in the build process, so we can switch back and
forth with maven.

And I think that we need gradle to install the artifacts in the user maven
local repo, because all our java projects use maven.
https://docs.gradle.org/current/userguide/maven_plugin.html#sub:installing_to_the_local_repository

And to make things easier, we should replace knife.lbl.gov with a proper
artifacts store (artifactory or nexus).

That was my 2cents.

**Comment by nathandunn** [comment]
I don’t think that gradle has replaced maven, but I think its definitely a well-supported standard. 

It works pretty readily with any maven repos .  . 

Unless you’re doing something particularly complicated with maven or require very specific artifacts, it should work roughly the same as well as import ant targets.  

Nathan

**Comment by jnguyenx** [comment]
Yes, I didn't say that it won't work, on the contrary.

But I see that as using a spork: it combines a fork and a spoon in a
awesome fashion, but who uses it?

**Pull request closed without merging**
